title: Access to Microphone Device
id: WIN-200609225055
author: Roberto Rodriguez @Cyb3rWard0g
playbook_link:
creation_date: 2020/06/09
platform: Windows
permissions_required:
  - User
attack_coverage:
  - technique: T1123
    tactics:
      - TA0009
hypothesis: Adversaries might be accessing the microphone in endpoints over the network.
description: |-
  An adversary can leverage a computer's peripheral devices (e.g., microphones and webcams) or applications (e.g., voice and video call services) to capture audio recordings for the purpose of listening into sensitive conversations to gather information.
  Based on some research from [@svch0st](https://twitter.com/svch0st) you can to determine when and how long a process had access to the microphone of an endpoint by monitoring the following registry key:
    * HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\.
validation_dataset:
  - type: mordor
    url: https://raw.githubusercontent.com/OTRF/mordor/master/datasets/small/windows/collection/msf_record_mic.zip
analytics:
  - name: Analytic I
    data_sources:
      - Microsoft-Windows-Sysmon/Operational
    false_positives: Medium
    description: Look for any creation or modification of registry keys under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\NonPackaged
    logic: |-
      SELECT EventID, Message
      FROM mordorTable
      WHERE Channel = 'Microsoft-Windows-Sysmon/Operational'
        AND EventID IN (12,13,14)
        AND LOWER(TargetObject) RLIKE '.*consentstore\\\\\\\microphone.*'
  - name: Analytic II
    data_sources:
      - Security
    false_positives: Medium
    description: Look for any creation or modification of registry keys under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\NonPackaged
    logic: |-
      SELECT EventID, Message
      FROM mordorTable
      WHERE LOWER(Channel) = 'security'
        AND EventID IN (4656,4663,4657)
        AND LOWER(ObjectName) RLIKE '.*consentstore\\\\\\\microphone.*'
detection_blindspots:
hunter_notes:
hunt_output:
  - category: signature
    type: SIGMA
    name: sysmon_camera_microphone_access
    url: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/sysmon_camera_microphone_access.yml
  - category: signature
    type: SIGMA
    name: win_camera_microphone_access
    url: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/win_camera_microphone_access.yml
references: |-
  * https://medium.com/@7a616368/can-you-track-processes-accessing-the-camera-and-microphone-7e6885b37072
